### ISSUE TITLE
How does the sync work

### ISSUE THREAD

**Issue by wilsonge** [joomla/core-translations#10]
Posting this here rather than DM'ing on glip just because it might be useful for others.

I can see a com_csp file for Farsi language. This file has been removed from core for nearly a month. So given the sync from crowdin has been relatively recent how does it still end up in this repo? I presume this is how the sync with crowdin is performed or similar?

ref: https://github.com/joomla/core-translations/blob/main/joomla_v4/translations/package/fa-IR/administrator/language/fa-IR/com_csp.ini

**Comment by conconnl** [comment]
I understand the question in the title, but not sure about the Farsi information. How can that Farsi file ever have been in the core?

At this moment the Sync from Crowdin to GitHub has never run yet. There is a small issue compared to the manual downloads, or you get too much strings or too less. (Crowdin is looking at the CLI)

The current translations in the repository (except German variants, Spanish and Russian) are from the old Crowdin. Downloaded manually and uploaded to this repository. 
We can enable the download, but this will just mean that we will miss all hidden strings (which are not translated, but require English as value)

**Comment by wilsonge** [comment]
The farsi file has never been in core - i was referring to the english version that was in core - i hadn't realised we weren't syncing from crowdin yet - that's my bad and makes sense
