### ISSUE TITLE
Add new language "IN / Marathi"for translating CMS

### ISSUE THREAD

**Issue by dilseaniket** [joomla/core-translations#114]
### Is your feature request related to a problem? Please describe.
Marathi is a language spoken by 83 million people in India. Joomla v4 doesn't have support for this language.

### Describe the solution you'd like
Please create setup for Marathi so that we can contribute translating Joomla CMS. Adding another willing contributor: @abhidesh128

**Comment by zero-24** [comment]
The issue has been moved to joomla/core-translation as requested.

**Comment by conconnl** [comment]
The language has been added to Crowdin, this means translations can be started.
I will be in touch for the additional needs, to make it usable for the whole Joomla! community

**Comment by particthistle** [comment]
As https://joomla.crowdin.com/cms/mr has been created, can this issue now be closed?

@dilseaniket and @abhidesh128 is there any further information you need at the moment to assist you with getting through the translations? The Enhancement Team are currently doing presentations to students around India in the lead up to applications opening for GSoC 2022, so there may be an opportunity to find more crowdsource translators to progress the language pack further faster.

**Comment by abhidesh128** [comment]
@particthistle, yes. This issue can be closed now. We think we have sufficient information to proceed and will be working on the translations.

>The Enhancement Team are currently doing presentations to students around India in the lead up to applications opening for GSoC 2022, so there may be an opportunity to find more crowdsource translators to progress the language pack further faster.

That's really great..! It will be more helpful.
