### ISSUE TITLE
4.0 Italian pack errors

### ISSUE THREAD

**Issue by infograf768** [joomla/core-translations#123]
There are still 2 strings containing wrong placeholders of the type `%S` instead of `%s` (which breaks in 8.1)

from admin com_admin.ini

line 27 `COM_ADMIN_EXTENSION_AVAILABLE="Disponibile %S"`

from com_joomlaupdate.ini

line 173 `INSTL_EXTENSION_AVAILABLE="Disponibile %S"`

**Comment by conconnl** [comment]
The language coordinators have been notified. 
Thank you
