### ISSUE TITLE
Chinese zh-CN errors

### ISSUE THREAD

**Issue by infograf768** [joomla/core-translations#141]
Site:
missing ending doube quotes
COM_CONTACT_EDIT_PUBLISHED_CONTACT="已发布的联系人
<img width="841" alt="Screenshot 2022-01-01 at 11 28 34" src="https://user-images.githubusercontent.com/869724/147848815-7df5e745-89f3-4792-a716-191736ac4a7b.png">

Admin: 

13 files do not escape double quotes correctly & other errors.
![Screenshot 2022-01-01 at 11 43 08](https://user-images.githubusercontent.com/869724/147848848-5d69e51b-8440-44d8-9b9d-bc3934ef0a79.png)

**Comment by conconnl** [comment]
I have sent an mail too: https://volunteers.joomla.org/joomlers/1933-zhou-yongjian
Haven't heard back on other communication for the last 2 months, I can't say when a fix will be performed.
Crowdin isn't used which automatically. makes sure quotes are added, I think they use GitHub, but I have no clue which repository.
