### ISSUE TITLE
Add new language "Oshindonga (Ndonga)" for translating Joomla! CMS

### ISSUE THREAD

**Issue by ohrionmartin** [joomla/core-translations#146]
[Ndonga](https://en.wikipedia.org/wiki/Ndonga_dialect), also called **Oshindonga**, is a [Bantu](https://en.wikipedia.org/wiki/Bantu_language) dialect spoken in [Namibia](https://en.wikipedia.org/wiki/Namibia). It is a standardized [dialect](https://en.wikipedia.org/wiki/Dialect) of the [Ovambo language](https://en.wikipedia.org/wiki/Ovambo_language). has a large number of speakers in Namibia and widely taught in Schools as a first language.

Other willing contributor: @Amunwe-ENE

Joomla! doesn't have support for this language, Please create setup for Ndonga so that we can contribute translating Joomla! CMS. @Amunwe-ENE and I are native Ndonga speakers with proficient understanding over it.

**List of its language codes:**

| Standard      | Code |
|    :----:   |    :----:   |
| ISO 639-1   | [ng](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=ng)       |
| ISO 639-2   | [ndo](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?code_ID=320)        |
| ISO 639-3   | [ndo](https://iso639-3.sil.org/code/ndo)        |
| Glottolog   | [ndon1254](http://glottolog.org/resource/languoid/id/ndon1254)        |
| Guthrie code   | [R.22](https://web.archive.org/web/20180203191542/http://goto.glocalnet.net/mahopapers/nuglonline.pdf)        |
| Linguasphere   | 99-AUR-lc        |

**Comment by infograf768** [comment]
Language tag would be `ng-NA`

**Comment by conconnl** [comment]
https://joomla.crowdin.com/cms/ng

**Comment by ohrionmartin** [comment]
Thank you @conconnl!

I will update the rest of the team and tell them to create Crowdin accounts to commence translation.
