### ISSUE TITLE
Joomla 3 Wrong Kazakh server installer xml-s

### ISSUE THREAD

**Issue by infograf768** [joomla/core-translations#150]
We get an error in install languages page because the language code is not available
`Notice: Undefined offset: 1 in /Applications/MAMP/htdocs/stagingcms/administrator/components/com_installer/views/languages/tmpl/default.php on line 68`
<img width="1172" alt="Screenshot 2022-01-18 at 08 42 17" src="https://user-images.githubusercontent.com/869724/149894337-14055318-57d7-410c-93f0-910b67724a55.png">

The reason is simple: the install xml are wrong on the server:
`https://update.joomla.org/language/details3/kk-KZ)_details.xml` => Extraneous `)`

(`https://update.joomla.org/language/details3/kk-KZ_details.xml` does exist.)

also 2 errors in translation list

`<extension name="Kazakh" element="pkg_kk-KZ)" type="package" version="3.9.23.1" detailsurl="https://update.joomla.org/language/details3/kk-KZ)_details.xml"/>;`

**Comment by zero-24** [comment]
Thanks looks like there is a typo on the downloads portal:
![image](https://user-images.githubusercontent.com/2596554/149989976-a11c082f-c7b5-462f-ba33-4e30bfd19436.png)

I have just requested access to that part of the site to fix the issue and temporary fixed it on the server but that will be overriden on the next update of the update server XMLs.

**Comment by zero-24** [comment]
Has been fixed by @conconnl thanks.
