### ISSUE TITLE
Pashto Afghanistan (ps-AF) 5.0.1.1 has empty <version> tag

### ISSUE THREAD

**Issue by pe7er** [joomla/core-translations#1502]
I was testing the installation of some languages in the Joomla 5.2 back-end, and ran into an issue with **Pashto Afghanistan (ps-AF)**
After I installed it my Joomla site notified me that there was an update available for that language.
Immediately after the update, it again notified that there was an update available
Then I noticed that the version tag was empty: ``<version/>``

The version tag is empty in all .xml files, see:
https://github.com/joomla/core-translations/blob/main/joomla_v5/translations/package/ps-AF/administrator/language/ps-AF/install.xml
https://github.com/joomla/core-translations/blob/main/joomla_v5/translations/package/ps-AF/administrator/language/ps-AF/langmetadata.xml
https://github.com/joomla/core-translations/blob/main/joomla_v5/translations/package/ps-AF/api/language/ps-AF/install.xml
https://github.com/joomla/core-translations/blob/main/joomla_v5/translations/package/ps-AF/api/language/ps-AF/langmetadata.xml
https://github.com/joomla/core-translations/blob/main/joomla_v5/translations/package/ps-AF/language/ps-AF/install.xml
https://github.com/joomla/core-translations/blob/main/joomla_v5/translations/package/ps-AF/language/ps-AF/langmetadata.xml
https://github.com/joomla/core-translations/blob/main/joomla_v5/translations/package/ps-AF/pkg_ps-AF.xml

Apparently, this needs to be fixed at CrowdIn, but I don't know where to fix it.
https://joomla.crowdin.com/cms/ps

Can someone else take care?

**Comment by tecpromotion** [comment]
I have informed the translator in charge.

**Comment by pe7er** [comment]
This problem is still present. 
No new language pack has become available since my earlier issue report
https://downloads.joomla.org/language-packs/translations-joomla5/downloads/joomla5-pashto-afghanistan
