### ISSUE TITLE
I see there is no Urdu (pakistan) translation in Joomla, I want to contribute, tell me how I can do ?

### ISSUE THREAD

**Issue by sayfrndship1234** [joomla/core-translations#151]
I see there is no Urdu (pakistan) translation in Joomla, I want to contribute, tell me how I can do ?

**Comment by conconnl** [comment]
Thanks for asking!
Everybody can help translate languages via our Crowdin platform.
Like Urdu at https://joomla.crowdin.com/u/projects/18/l/ur

**Comment by sayfrndship1234** [comment]
i already posted question there, got very late reply there, let me see that, but tell me i want people to know that I am translating the urdu, will it be possible. like by my name, or any other info as i m joomla expert as well a registered user too.
