### ISSUE TITLE
Faulty update XML for Catalan language pack

### ISSUE THREAD

**Issue by pe7er** [joomla/core-translations#1532]
After installing the available updates for languages to Joomla 5.2.2, the Catalan and Latvian language packs again had an update available:

![Image](https://github.com/user-attachments/assets/26fa84fa-82ad-4570-b500-8768df818a53)
 
The update URL states that 5.2.2.2 is available, 
but the language pack for 5.2.2.2 has a pkg_ca-ES.xml that is for 5.2.2.1

**Update URL**
https://update.joomla.org/language/details5/ca-ES_details.xml

```xml
<updates>
<update>
<name>Joomla! 5 - Catalan</name>
<description>This is the Catalan Language Pack for Joomla! 5.2.2 (v2)</description>
<element>pkg_ca-ES</element>
<type>package</type>
<version>5.2.2.2</version>
<downloads>
<downloadurl type="full" format="zip">https://downloads.joomla.org/language-packs/translations-joomla5/downloads/joomla5-catalan/5-2-2-2/ca-es_joomla_lang_full_5-2-2v2-zip?format=zip</downloadurl>
</downloads>
```

**pkg_ca-ES.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<extension type="package" method="upgrade">
	<name>Catalan (ca-ES) Language Pack</name>
	<packagename>ca-ES</packagename>
	<version>5.2.2.1</version>
```

**Comment by tecpromotion** [comment]
I have informed the translator in mattermost.
