### ISSUE TITLE
Faulty update XML for Latvian Language pack

### ISSUE THREAD

**Issue by pe7er** [joomla/core-translations#1533]
After installing the available updates for languages to Joomla 5.2.2, the Catalan and Latvian language packs again had an update available:

![Image](https://github.com/user-attachments/assets/26fa84fa-82ad-4570-b500-8768df818a53)
 

The update URL states that 5.2.2.2 is available, 
but the language pack for 5.2.2.2 has a pkg_lv-LV.xml that is for 5.2.2.1

**Update URL**
https://update.joomla.org/language/details5/lv-LV_details.xml

```xml
<updates>
<update>
<name>Joomla! 5 - Latvian</name>
<description>This is the Latvian Language Pack for Joomla! 5.2.2 (v2)</description>
<element>pkg_lv-LV</element>
<type>package</type>
<version>5.2.2.2</version>
<downloads>
<downloadurl type="full" format="zip">https://downloads.joomla.org/language-packs/translations-joomla5/downloads/joomla5-latvian/5-2-2-2/lv-lv_joomla_lang_full_5-2-2v2-zip?format=zip</downloadurl>
</downloads>
```

**pkg_lv-LV.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<extension type="package" method="upgrade">
	<name>Latvian (lv-LV) Languge Pack</name>
	<packagename>lv-LV</packagename>
	<version>5.2.2.1</version>
```

**Comment by tecpromotion** [comment]
> This problem is still present. A new language pack has not yet been released for Joomla 5.2.3: https://downloads.joomla.org/language-packs/translations-joomla5/downloads/joomla5-latvian

see mail
