### ISSUE TITLE
en-US Language pack

### ISSUE THREAD

**Issue by brianteeman** [joomla/core-translations#185]
Once again multiple errors in this language pack are causing errors. Today alone there were two bug reports to core which were just errors in this language pack.

I randomly checked three files and ignoring issues with strings not being 100% up to date I found strings in Russian, Polish and others that were simply wrong and copy pasted from the wrong place.

#35 was the previous report.

**Comment by brianteeman** [comment]
Some quick examples

![image](https://user-images.githubusercontent.com/1296369/153922353-7ad34c52-d4ce-47d7-be44-10efc28359e2.png)

![image](https://user-images.githubusercontent.com/1296369/153922445-8ceedb7d-1c61-4c85-ae06-fcb653dd45c1.png)

![image](https://user-images.githubusercontent.com/1296369/153922585-4bee30ab-426a-4f36-91ce-f488d1a79782.png)

![image](https://user-images.githubusercontent.com/1296369/153922651-cb0cc222-6447-4b74-95b5-e308f687f93f.png)

![image](https://user-images.githubusercontent.com/1296369/153922787-9f6b6e82-c86c-42fb-a22f-02ccfc7150e7.png)

**Comment by tecpromotion** [comment]
@particthistle can you please check this issue within crowdin

**Comment by brianteeman** [comment]
@tecpromotion these are just random examples. The two issues reported by @n6rej today were https://github.com/joomla/joomla-cms/discussions/37028 and https://github.com/joomla/joomla-cms/issues/37026

Isn't someone other than the translator supposed to approve everything?

**Comment by tecpromotion** [comment]
> Isn't someone other than the translator supposed to approve everything?

@particthistle is the proofreader for en-us in crowdin

**Comment by tecpromotion** [comment]
In the case of the first string, this was loaded into crowdin and released by the proofreader. This seems to have been in place for a very long time (July 2021).

see: https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-english-us/4-0-0-11

**Comment by infograf768** [comment]
Crowdin J4 en-US:
<img width="1152" alt="Screenshot 2022-02-15 at 09 40 18" src="https://user-images.githubusercontent.com/869724/154024618-9241615c-6c88-4fc3-8278-5db14a1f4467.png">

That string is perfectly OK in en-US 3.x package as installed by 3.x, **BUT not in Crowdin for 3.x**

Package
`COM_USERS_USERS_ERROR_CANNOT_DEMOTE_SELF="You can't remove your own Super User permissions."`

Crowdin 3.x
![Screenshot 2022-02-15 at 09 53 46](https://user-images.githubusercontent.com/869724/154026749-8d2eef76-380b-4899-8499-e9fd4cc0a712.png)

Looks like whoever originally just copied crowdin 3.x contents to the crowdin j4 and did not check with the en-US coordinator at the time if that version was OK with what was in the real package... The en-US coordinator was steve4c `<authorEmail>stevec4@comcast.net</authorEmail>`

**Comment by particthistle** [comment]
Rectifying problems currently as well as translating remaining additions for 4.1.

Next update of en-US language pack will be uploaded shortly and fix the ones @brianteeman has identified, as well as several others identified while reviewing the files identified.

The best place for anyone finding an error in a translation to resolve it is to simply go to https://joomla.crowdin.com/cms and add a crowdsourcing translation correction. That will then notify the proofreader (me in this case) and I can then proofread, approve and package the update for release.

Watch for 4.1.1 versions in the next 24 hours.
