### ISSUE TITLE
Issues related to the new platform

### ISSUE THREAD

**Issue by sujithranga** [joomla/core-translations#191]
**Issue Description**

**Language:** Sinhala
**Native name:** සිංහල
**Code:** si
**Crowdin ID:** [@helabasa](https://crowdin.com/profile/helabasa)
**Current Status:** Joomla CMS 3 Translator & Proofreader
**Problem:** We don't have proofreader right/permission on new enterprise platform

**Projects list**
1. Joomla CMS
2. Joomla Official Extensions
3. Joomla Official Template
4. Joomla Official Website

Also, can you enable sinhala language for below projects and apply same permission?

1. Easyblog
2. Easysocial
3. Easyarticles
4. Easydiscuss
5. Payplans
6. Komento
7. Yoursites
8. Opening hours module
9. RSForm
10. RStickets
11. RSmail
12. RSfiles
13. RSdirectory
14. RSmembership
15. RSfirewall
16. RSfeedback
17. RSevents
18. RSblog
19. Conversekit
20. RSseo
21. RSmediagallery
22. RScomments
23. Shika
24. Jbolo
25. Zero-24
26. Joomla marketing resources

**Comment by tecpromotion** [comment]
@sujithranga i will check this in crowdin today.

**Comment by sujithranga** [comment]
And we need Joomla 4 language pack as well. please use/create only with **"si" language code** instead "si_LK"
https://downloads.joomla.org/language-packs/translations-joomla4

Old language pack and team (joomla 3), they're no longer active
https://downloads.joomla.org/language-packs/translations-joomla3#si-lk
