### ISSUE TITLE
[4.1] he-IL installation langmetadata.xml has no name & no native name

### ISSUE THREAD

**Issue by infograf768** [joomla/core-translations#199]
```
<?xml version="1.0" encoding="utf-8"?>
<metafile client="installation">
	<name/>
	<version>4.1.0</version>
	<creationDate>February 2022</creationDate>
	<author/>
	<copyright>(C) 2005 Open Source Matters, Inc.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<files>
		<filename>joomla.ini</filename>
	</files>
	<metadata>
		<name/>
		<nativeName/>
		<tag>he-IL</tag>
		<rtl>1</rtl>
	</metadata>
	<params/>
</metafile>
```

**Comment by tecpromotion** [comment]
Good morning @infograf768 
Thank you for this issue.
I will contact the translator on crowdin.

@HLeithner @zero-24 @conconnl @bembelimen
Is there any way we can usefully put some checks together here?

**Comment by infograf768** [comment]
Hello. There is another problem:
he-IL should NOT be proposed at installation time as there is NO core language pack available.
Not speaking about the fact that most of the installation he-IL joomla.ini is untranslated...

**Comment by zero-24** [comment]
Maybe a similiar workflow works here as we did with the check php code?

Who can help here and understands the workflow things here on GitHub?

**Comment by tecpromotion** [comment]
> Hello. There is another problem: he-IL should NOT be proposed at installation time as there is NO core language pack available. Not speaking about the fact that most of the installation he-IL joomla.ini is untranslated...

I submitted a quick PR #200.
Of course, it has to be clarified why a) it is not loaded cleanly from crowdin here, since it seems to be in there
and b) why the joomla.ini is so poorly translated there.

@infograf768 do you want to take a look at the PR? Thanks

**Comment by infograf768** [comment]
I think the reason why we have no pack and no real translation (even the localise.php are wrong on crowdin) is that we just have no language coordinator for Hebrew. 
Initial stuff may have been copied from the 3.x crowdin which may not even have been used by the Hebrew TT at the time as he had stopped collaboration for a long time.
FYI, last 3.x Hebrew pack is 3.1.1.2.

Therefore the only solution in our case (Your PR has been refused) is to prevent he-IL to be added to core...

**Comment by tecpromotion** [comment]
PR is closed. The changes must be made in crowdin. There, however, they look correct.

**Comment by tecpromotion** [comment]
Thank you for your research @infograf768 

Then we need to delete the files and expose them in the GitHub action he-IL. Right @HLeithner ?

**Comment by HLeithner** [comment]
to my knowledge it looks like that the string are not approved so no translation is in crowdin "done"

**Comment by tecpromotion** [comment]
see #202 

There is no question that we are tackling this issue in principle.
