### ISSUE TITLE
Installation languages en-US, en-NZ, en-CA have some wrong ini string values

### ISSUE THREAD

**Issue by infograf768** [joomla/core-translations#213]
These are are just copies of en-AU.
```
BUILD_INCOMPLETE_LANGUAGE="English AU"
BUILD_NOXML_LANGUAGE="English AU"
BUILD_MIN_PHP_ERROR_LANGUAGE="English AU"
```
Example for en-NZ, the value `English AU` should be `English NZ`, etc.

**Comment by tecpromotion** [comment]
@particthistle please check and fix in crowdin. Thanks.

@infograf768 thanks.

**Comment by particthistle** [comment]
This can be closed. Updated in Crowdin and will be in the next version updates for en-CA and en-NZ. en-US was not affected.
