### ISSUE TITLE
Workflow core-get-language-source-v4.yml is executed on forks

### ISSUE THREAD

**Issue by zero-24** [joomla/core-translations#28]
Hi, the workflow: core-get-language-source-v4.yml is beeing executed on forks which fails cause no data are beeing attached. So please make sure its only triggered for the main repo :)

![image](https://user-images.githubusercontent.com/2596554/129470133-26791071-2ab1-42e2-b955-a22d61254e31.png)

Btw it only claims that i triggered something for unknown reason. I might have updated the branch to the newest version but i have not manually triggered anything like that.

**Comment by conconnl** [comment]
Looking at your fork is being triggered every day.
https://github.com/joomlagerman/core-translations/actions/workflows/core-get-language-source-v4.yml

Step 1 isn't triggered, so it seems the improvement done by George need to be extended to step 2 as well.

**Comment by zero-24** [comment]
Thanks our repo has been updated will report back whether we still get error or not :)

**Comment by zero-24** [comment]
Looks like its fixed now thanks!
