### ISSUE TITLE
Redirect not working with php 8.1

### ISSUE THREAD

**Issue by ita4012** [joomla/core-translations#311]
As stated in this thread https://forum.joomla.org/viewtopic.php?f=708&t=994471 , it seems there's an issue in italian joomla language pack.

Best regards

**Comment by tecpromotion** [comment]
@ita4012 please see my comment https://forum.joomla.org/viewtopic.php?f=708&t=994471&p=3662901#p3662901

**Comment by ita4012** [comment]
Thanks

**Comment by ita4012** [comment]
I read your reply in https://forum.joomla.org/viewtopic.php?f=708&t=994471&p=3662901#p3662901, but I still use Joomla 3.10.1. Redirecting still not working with php 8.1, so far, so I have to switch back to 7.4, again.
