### ISSUE TITLE
Validate PHP files

### ISSUE THREAD

**Issue by HLeithner** [joomla/core-translations#47]
Before merging language updates we should validate the PHP files.
At least a syntax check should be done something like:
```sh
find . -name *.php -exec php -l "{}" ;
```

suggested in https://github.com/joomla/joomla-cms/issues/35401

**Comment by conconnl** [comment]
Direct validator in the get action
https://github.com/joomla/core-translations/blob/main/.github/workflows/remote-get-japanese.yml#L61

Validator for Pull Requests
https://github.com/joomla/core-translations/blob/main/.github/workflows/_check-php-code.yml
