### ISSUE TITLE
uk-UA language pack is missing pkg_uk-UA.xml

### ISSUE THREAD

**Issue by wojsmol** [joomla/core-translations#481]
Latest uk-UA language pack is missing pkg_uk-UA.xml witch is causing rsync synchronisation error https://github.com/joomla/core-translations/actions/workflows/remote-get-ukrainian.yml

**Comment by tecpromotion** [comment]
see https://github.com/Joomla-Ukraine/uk-UA/issues/29

thanks @wojsmol
