### ISSUE TITLE
Galician translation download

### ISSUE THREAD

**Issue by pabloarias** [joomla/core-translations#487]
Hi:

Where can people download Galician translation, please?

It's not available here: https://downloads.joomla.org/es/language-packs/translations-joomla4

But it's available to translate in Crowdin.

Thank you and best regards

**Comment by tecpromotion** [comment]
Hi @pabloarias 
There is currently no active proofreader for the language package. If you have the means to take on this job, I would be happy to receive an email from you to the following address: stefan.wendhausen@community.joomla.org

kind regards, Stefan

**Comment by pabloarias** [comment]
I wrote an email to confirm it but no response yet.

**Comment by tecpromotion** [comment]
Hi @pabloarias 
Unfortunately, I never received an email.

**Comment by pabloarias** [comment]
Hi. Sent again, received?

Thanks!
