### ISSUE TITLE
North Macedonian Language Pack - Joomla 4

### ISSUE THREAD

**Issue by oidafuxmichi** [joomla/core-translations#496]
Hello,

I need a langauge pack for **Northern Mazedonia** (mk) - it existed in Joomla 3, but does not in **Joomla 4**.

Can anyone help?

Thank you very much,
Michael

**Comment by wojsmol** [comment]
cc @tecpromotion mk-MK language pack is not available for [download](https://downloads.joomla.org/language-packs/translations-joomla4).

**Comment by tecpromotion** [comment]
It's ready. See https://joomla.crowdin.com/cms/mk

I can check this next week.
It is the proofreader's job to create the package and make it available on downloads. I am happy to initiate that as well.

**Comment by oidafuxmichi** [comment]
Thank you very much! It' an EU Project for children.

Thanks,
Michael

Am Fr., 28. Okt. 2022 um 20:28 Uhr schrieb Stefan Wendhausen <
***@***.***>:

**Comment by oidafuxmichi** [comment]
Stefan,

danke für den Link, aber wie kann ich das für Joomla 4 runterladen?

Danke,
Michael

Am Fr., 28. Okt. 2022 um 20:28 Uhr schrieb Stefan Wendhausen <
***@***.***>:

**Comment by oidafuxmichi** [comment]
Und danke für die schnelle Antwort!

Michael

Am Sa., 29. Okt. 2022 um 00:30 Uhr schrieb Michael Eisner <
***@***.***>:

**Comment by tecpromotion** [comment]
@oidafuxmichi the responsible proofreader will create a package in the coming days and offer it for download. Please be patient, Joomla is 100% based on volunteers and their voluntary commitment.

**Comment by oidafuxmichi** [comment]
Thank you very much!

Am Di., 1. Nov. 2022 um 14:48 Uhr schrieb Stefan Wendhausen <
***@***.***>:

**Comment by oidafuxmichi** [comment]
It should appear here, right?
https://downloads.joomla.org/de/language-packs/translations-joomla4

Thank you, Michael

Am Mi., 2. Nov. 2022 um 08:03 Uhr schrieb Michael Eisner <
***@***.***>:

**Comment by tecpromotion** [comment]
Yes.
