### ISSUE TITLE
Dari wrong language code

### ISSUE THREAD

**Issue by infograf768** [joomla/core-translations#56]
Dari language code should not be `fa-AF` as this code is a IETF code.  Until now, we use ISO codes for Joomla languages.
The real ISO Code is `prs-AF` as in J3.
See https://en.wikipedia.org/wiki/Dari

<img width="318" alt="Screen Shot 2021-09-10 at 11 25 48" src="https://user-images.githubusercontent.com/869724/132833371-ccab02b9-fcea-4251-84c0-93e9fbdde76f.png">

This should be modified in all xmls and the crowdin list of languages and also explained to the TT coordinator for this language.

**Comment by conconnl** [comment]
As replied it Crowdin as well. 
This code is correct for various ambiguous reasons, it doesn’t matter what was done in the past. We are in a new world more then 10 years further, the language owners decide how things work and why. 
There will be more fa- languages available for various countries. 

This doesn’t have too be changed, no matter if it was used for Joomla 3. That version started 8 years ago.

**Comment by Bakual** [comment]
@conconnl That's not correct. The "language owners" (I think you mean the translation team?) can't decide by themself what code they use. They need to follow the guidelines from the Joomla CMS. If thise guidelines say we use ISO codes, then the language packs have to follow that.
Changing that guidelines is a production decision, not a translator decision.

**Comment by infograf768** [comment]
Dari is a unique language based on the evolution of West Persian in Afghanistan while Pashto, the other official language of Afghanistan is an evolution of Eastern Iranian language.

Why would you use the ISO ps-AF for Pashto and fa-AF for Dari as they are both variations of Persian?
You absolutely can't compare them with the variations of German in Europe for example.

One can, evidently use fa-US or fa-FR to adress specifically a community speaking Farsi in the US or France. The situation is NOT comparable to the 2 official languages of Afghanistan.

FYI Tajik is also a Persian based language but it has its own iso code tg. Ouzbek the same. 

Note: ISO codes are not dead because we used them 10 years ago. Saying this is pure ignorance.

**Comment by safajuy** [comment]
> 
> 
> Dari is a unique language based on the evolution of West Persian in Afghanistan while Pashto, the other official language of Afghanistan is an evolution of Eastern Iranian language.
> 
> Why would you use the ISO ps-AF for Pashto and fa-AF for Dari as they are both variations of Persian?
> You absolutely can't compare them with the variations of German in Europe for example.
> 
> One can, evidently use fa-US or fa-FR to adress specifically a community speaking Farsi in the US or France. The situation is NOT comparable to the 2 official languages of Afghanistan.
> 
> FYI Tajik is also a Persian based language but it has its own iso code tg. Ouzbek the same.
> 
> Note: ISO codes are not dead because we used them 10 years ago. Saying this is pure ignorance.

thanks @infograf768 
Your explanation was complete and comprehensive. I'm glad that someone like you on the Joomla! Team

**Comment by safajuy** [comment]
I have been researching in the field of Persian linguistics for several years.
Dari is another form of Persian language whose words are different in some cases.
(To the extent of new words such as helicopter and TV, etc.)
Linguists in both countries have tried to have as many similar words as possible to keep Persian alive. But they were somewhat unsuccessful.

Dari behaves like a dialect. Even in Iran itself, Persian language is seen in different forms, but we refer to them as a dialect, not a language!
Dari can be considered as one of the branches of Persian language. The code provided for this topic is incorrect. I think the fa-AF should be used

**Comment by Bakual** [comment]
There is also the thing that we already used prs-AF and fa-IR for years for Dari and Farsi respectively.
If you now change the language pack from prs-AF to fa-AF it means each user has to uninstall the old one and install the new one manually. Or we have to do additional custom code and workarounds to let the updater manage this automatically, which is not such an easy task. It means having a special rule in the update manifest, an update script which removes the old prs-AF files and adjusts the content language (if present) to the new tag. Also a new "flag" has to be shipped with the CMS.

In the end, there is no gain at all in changing it. The used language code is mainly an internal thing. How it appears in the URL can be adjusted by the user in the content language.

The currently used code isn't wrong, so the main question to me is: Why change? What is the reason for it?

**Comment by safajuy** [comment]
I am currently a Dari translator for Joomla!
The code that was put at the beginning was strange to me, why do two Persian languages have separate labels?
The Dari language itself is a branch of Persian. In fact, the full name of this language is "Dari Persian".
Naturally, if an upgrade is to be made, it is possible with a simple installation and removal of the language, and it is not complicated. Due to the download rate of this language, the reluctance of users and even the translation team is that this code is unfamiliar to Afghan users. Shouldn't the user experience be involved in this?

**Comment by Bakual** [comment]
> The code that was put at the beginning was strange to me, why do two Persian languages have separate labels?
> The Dari language itself is a branch of Persian. In fact, the full name of this language is "Dari Persian".

As I wrote above, it would be similar to Swiss German and German in my eyes. Even dialects have their own ISO code.

> Naturally, if an upgrade is to be made, it is possible with a simple installation and removal of the language, and it is not complicated.

This can be done manually by the user, yes. But users will not see the updated pack in the extension manager. So how will they know that they need to uninstall their prs-AF and install fa-AF?

Due to the download rate of this language, the reluctance of users and even the translation team is that this code is unfamiliar to Afghan users. Shouldn't the user experience be involved in this?

I actually doubt that users care about the language code used. I may bew rong with that, but when I search for a language, I look for the name, not for the code. When I search for "persian" I get Dari Persian (prs-AF) and Persian (fa-IR). Maybe I take fa-IR then because Dari is outdated, but I certainly wouldn't care about the language code. That code doesn't matter.
However if you have both Dari Persian and Persian installed, you need different URL codes for both languages. So "prs" and "fa" would be fine, right? Otherwise you probably get "fa" and "fa-AF" as URL codes.

**Comment by infograf768** [comment]
@safajuy 
`fa` is a **macrolanguage**, i.e. all variations of Farsi (dialects) come from `fa` originally.
It does not mean that a specific variation of this macrolanguage should use `fa` as lang tag, specially when, for a said country code, there are MANY variations of Farsi, which is exactly the case in Afghanistan.

The `fa` tag is traditionally used for the variation of Farsi in Iran **and the unique official language in that country.** In fact, if we were even more precise, we would use `pes`

What shall we do if some Tajik team creates a language for Joomla? Why shall we use the 3 letters lang code for Tajik and not for Dari?

<img width="374" alt="Screen Shot 2021-09-12 at 12 07 48" src="https://user-images.githubusercontent.com/869724/132983587-1c4d8e41-b2f4-4504-8cc2-c5b98aa89cbd.png">

Isn't it rather that your team/site wants to change the target of your work which makes you insist on the use of `fa`?

https://translate.google.com/translate?hl=en&sl=fa&tl=en&u=http%3A%2F%2Fwww.joomlapersian.com%2Ffa%2Fnews%2Fsite-news%2F18-joomlapersian-new-change.html

> These changes are due to the fact that the Joomla Persian team intends to localize this popular content management system in Persian, **without restricting borders and ethnicity**, and provide it to its users

(bold by me)

**Comment by safajuy** [comment]
I am an Iranian. My language is Persian and I have been studying my mother tongue and its roots for many years (before the birth of Joomla).
My goal is to use translations without restrictions for Persian language users. Without borders and without geography.
If you feel your language code is correct, I have nothing to say :)

I gave my description to Joomla's account in Crowdin. You can ask them for translation sensitivity.
Good luck to all friends

**Comment by Saeedghb** [comment]
@infograf768 

I think we are currently following a double standard in language tags. Iranian Persian follows ISO 639-1 and Dari Persian follows ISO 639-3.

If we follow the ISO 639-1 standard, all Persian language variants in different countries should use the fa tag. For example: fa-IR, fa-AF, and fa-TJ

If we want to follow the ISO 639-3 standard, Iranian Persian should also use the pes-IR tag. and prs-AF should be used for Dari Persian and tgk-TJ for Tajiki Persian as well.

As an Iranian and a member of the translation team, who is more familiar with the Persian language and its variants, I think this combination is appropriate:
fa-IR
fa-AF
fa-TJ

**Comment by Bakual** [comment]
That is according to our rules, not a double standard.
We use 639-1 (two-letter-code) where possible, and if there is no match we use 639-3 (three-letter-code).
Probably, the fa-IR one was first and then afterwards prs-AF came additionally.

Again: If the language is the same, used in different countries with only minor differences, then fa-AF and fa-IR would be fine. For example en-GB and en-US where the difference is marginal (some z instead of s and such things).
My understanding of the persian packs is that there are more differences.

**Comment by Bakual** [comment]
What I don't understand: Why do you even want to change the code of an existing pack? There is no gain from my point of view.
We can discuss about the code of new packs, but existing packs should just keep their code.

**Comment by infograf768** [comment]
ISO, whatever the number is only one standard.
It is preferred to use ISO 639-1 when possible with the country code.
It means that `fa` (commonly used for Iranian Persian) should be used when it concerns exactly Iranian Persian whatever the country. As I said already above, we could be more precise by using `pes`, but this would be against the usages for this language.

Dari Persian, once more, is a unique language based on the evolution of West Persian in Afghanistan.
As Dari is not present in ISO 639-1, we look at other ISO and find it explicitely in ISO 639-3.

https://iso639-3.sil.org/code_tables/639/data/p?page=1

<img width="1122" alt="Screen Shot 2021-09-16 at 09 43 33" src="https://user-images.githubusercontent.com/869724/133571472-3f05a0a6-e884-4f53-905f-eb98bb23b991.png">

The best demonstration of this decision that we took years ago is what we do for Tajik.

Tajik is NOT `fa`. As I said again above, what would you do with Tajik spoken is Afghanistan with your system?
Tajik is `tg` in ISO 639-1 and `tgk` in ISO -3 so we prefer `tg`

https://lingohub.com/academy/best-practices/iso-639-1-list
<img width="1008" alt="Screen Shot 2021-09-16 at 09 53 34" src="https://user-images.githubusercontent.com/869724/133572944-29c2bc8c-35ae-404a-ad76-1b246c0a2285.png">

Which means in this case, as Tajik is NOT an official language in Afghanistan that we should use.
`tg-TJ` for the official language in Tajikistan
and
`tg-AF` for the Tajik spoken in Afghanistan

I have now explained the logic of these ISO codes. They have nothing to do with knowledge or not of these languages, they are only NORMALIZED codes we should follow to differentiate the languages.

I am not interested by arguing anymore on this.

OOps, just saw @Bakual already replied.

**Comment by infograf768** [comment]
https://github.com/joomla/core-translations/pull/76

Congratulations to @conconnl 
You get the prize.
