### ISSUE TITLE
en-AU Date formats incorrectly mixed?

### ISSUE THREAD

**Issue by RussW** [joomla/core-translations#568]
4.2.2.3 - 4.2.7.1 
The date formats( DATE_FORMAT_* ) in the various joomla.ini language files appear to mixed [AU/GB] & US formats, causing an incorrect/invalid date on various article publishing dates (value/data attributes & display) in administration and subsequently causing issues with correct sorting in both Admin and Frontend.

**Comment by tecpromotion** [comment]
I have forwarded this to the coordinator for the language package.

**Comment by particthistle** [comment]
4.2.8.2 will have the reset base strings matching en-GB defaults shortly. Just waiting for Crowdin to compile the download.

This was previously resolved ~18 months ago, but I'm not sure what burped in Crowdin to get the values to reset again.

If you do need to fix it manually, here's the list of constants and default values that you can use to make temporary language overrides (for the benefits of other readers, as I know you're more than aware of this @RussW :))

DATE_FORMAT_CALENDAR_DATE="%Y-%m-%d"
DATE_FORMAT_CALENDAR_DATETIME="%Y-%m-%d %H:%M:%S"
DATE_FORMAT_FILTER_DATE="Y-m-d"
DATE_FORMAT_FILTER_DATETIME="Y-m-d H:i:s"
DATE_FORMAT_JS1="y-m-d"
DATE_FORMAT_LC="l, d F Y"
DATE_FORMAT_LC1="l, d F Y"
DATE_FORMAT_LC2="l, d F Y H:i"
DATE_FORMAT_LC3="d F Y"
DATE_FORMAT_LC4="Y-m-d"
DATE_FORMAT_LC5="Y-m-d H:i"
DATE_FORMAT_LC6="Y-m-d H:i:s"

**Comment by particthistle** [comment]
4.8.2.2 is now available via the Joomla Language Pack Download system. It should show as an update in Joomla 4 now.
