### ISSUE TITLE
Scottish Gaelic

### ISSUE THREAD

**Issue by multizone-uk** [joomla/core-translations#702]
I saw that there used to be a Scottish Gaelic Language Pack for Joomla! 2.5.7.1 (eons ago). It is at  [Joomla! 2.5 - Scottish Gaelic](https://downloads.joomla.org/language-packs/translations-joomla25/downloads/joomla25-scottish-gaelic).

I'd love to get this going with 4.x. I don't know Scottish Gaelic sadly but happy to try to do the legwork and get help from Scot friends if someone would point me at 'how to update an old language pack' or similar doc. I've done localisation projects before for European languages so Im familiar with the concepts. 

Or indeed happy to help if someone is doing this?

**Comment by zero-24** [comment]
Hi,

we are using crowdin enterprise to manage the translations: https://joomla.crowdin.com/cms

We need to enable scottish there, as soon as @tecpromotion is back he will take a look into it.

**Comment by tecpromotion** [comment]
Hi @multizone-uk 
I am back from holiday.
To avoid discussing all this here on GitHub, do you already have a Joomla Mattermost account?
Feel free to write me directly.
