### ISSUE TITLE
fa-IR 4.0.0v1 pack issues

### ISSUE THREAD

**Issue by infograf768** [joomla/core-translations#72]
1. The manifest does not contain the updateserver
```
<updateservers>
		<server type="collection" priority="1" name="Accredited Joomla! Translations"/>
	</updateservers>
```

2. The jalali date is no more present because of missing code in localise.php and missing installing the calendar js in media.

----Missing code
A. in  site install.xml missing
```
    <files>
		<folder>/</folder>
        <filename file="meta">install.xml</filename>
      </files>

	<media destination="fa-IR">
	    <filename>index.html</filename>
		<filename>js/index.html</filename>
		<filename>js/calendar-setup.js</filename>
		<filename>js/calendar.js</filename>
        <filename>js/calendar-setup-uncompressed.js</filename>
		<filename>js/calendar-uncompressed.js</filename>
	</media>
```
files which are present in the js folder
<img width="285" alt="Screen Shot 2021-09-24 at 11 21 50" src="https://user-images.githubusercontent.com/869724/134651290-2ff0091d-b7d8-48cc-924b-7132c4324a6c.png">

B. in localise.php missing the whole `class fa_IRDate extends JDate {`

**Comment by infograf768** [comment]
I also remarked another error:
The pack name is `fa-IR_joomla_lang_full_4.0.1v4.zip` , but the manifest version (and all xml versions) is `<version>4.0.0.v1</version>`

**Comment by infograf768** [comment]
I helped the TT correct his pack and it will be uploaded soon I guess.

The problem remains for the 1000+ people who installed the existing pack which does not contain the updateserver.
I remember that there was a similar problem first en-US packs and I have no idea how it was solved.

**Comment by infograf768** [comment]
@joomlafarsi
The emails I send to you are not accepted by your server.

Here is the content
-----------------
Hello

I corrected your pack.

The name of the zip: it should not contain a dash before the v, therefore it is
fa-IR_joomla_lang_full_4.0.3v1.zip

I corrected your localise.php files to use J4 code, i.e.

use Joomla\CMS\Date\Date;  // added

jimport('joomla.utilities.date’); // deleted

And further down
class fa_IRDate extends Date { // instead of JDate

I added the js folder containing the jalali js files in the fa-IR SITE language/fa-IR/ folder
![Screen Shot 2021-09-29 at 13 58 28](https://user-images.githubusercontent.com/869724/135801249-d9599f32-73d8-4970-b309-a6410921d082.png)

I modified the install.xml for site language/fa-IR/ to install the js files.

<?xml version="1.0" encoding="utf-8"?>
<extension client="site" type="language" method="upgrade">
	<name>Persian (fa-IR)</name>
	<tag>fa-IR</tag>
	<version>4.0.3.1</version>
	<creationDate>September 2021</creationDate>
	<author>Persian Translation Team</author>
	<authorEmail>info@joomlafarsi.com</authorEmail>
	<authorUrl>www.joomlafarsi.com</authorUrl>
	<copyright>Copyright (C) 2005 - 2021 Joomlafarsi.com and Open Source Matters, Inc.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<description>fa-IR site language</description>
	<files>
		<folder>/</folder>
		<filename file="meta">install.xml</filename>
	</files>

	<media destination="fa-IR">
		<filename>js/calendar-setup.js</filename>
		<filename>js/calendar.js</filename>
		<filename>js/calendar-setup-uncompressed.js</filename>
		<filename>js/calendar-uncompressed.js</filename>
	</media>
	<params/>
</extension>

Here is the new pack which I tested OK for the Jalali  date

[fa-IR_joomla_lang_full_4.0.3v1.zip](https://github.com/joomla/core-translations/files/7275778/fa-IR_joomla_lang_full_4.0.3v1.zip)


FIRST NOTE:
There are errors in your site com_finder.ini
English
COM_FINDER_QUERY_TOKEN_EXCLUDED="<span class=\"term\">%s</span> should be excluded"

COM_FINDER_QUERY_TOKEN_OPTIONAL="<span class=\"term\">%s</span> is optional"
COM_FINDER_QUERY_TOKEN_REQUIRED="<span class=\"term\">%s</span> is required”

Your file
COM_FINDER_QUERY_TOKEN_EXCLUDED="<span class

COM_FINDER_QUERY_TOKEN_OPTIONAL="<span class
COM_FINDER_QUERY_TOKEN_REQUIRED="<span class

There is an error in your MOD_ARTICLES_NEWS_FIELD_FEATURED_LABEL="مطالب ومقاله فعلی را حذف کنید
(Missing ending “)


NOTE: there is a remaining problem.
Your former pack has been downloaded by more than a thousand users and did not contain the update servers.
This means that they will never be proposed an update.


You nevertheless  should ask wilco to delete the old pack and ask him if there is a solution for the people to update their packs to the new corrected one.

JM

**Comment by conconnl** [comment]
> The name of the zip: it should not contain a dash before the v, therefore it is fa-IR_joomla_lang_full_4.0.3v1.zip

The system created by production on the download website generates the file name. 
The files name are always correct, no matter what is supplied or people think.

**Comment by infograf768** [comment]
> Translators and Proofreaders are not developers, etc.

Woshhh, I was not aware of that... ROTFLOL

The message was intended as a reply to Abolhassan Firoozmandan (joomlafarsi).
He knows very well what these js mean and what has to be added in the fa-IR localise.php.  They have not changed since 3.x which joomlafarsi has maintained for years. The jalali date code was provided by Production at the time. 
AFAIK, that kind of pack has to be custom created even if using crowdin is used in a first step as there is no way otherwise to add a fa-IR.css, modified localise.php, a js folder with the correct js files in it and a modification to install these js in the install.php. BTW, this also concerns prs-AF.
If this has changed, then somebody not ignorant should control and help the TT before a wrong pack is posted...
As for programs-department, no comment.

> The file name are always correct, no matter what is supplied or people think.

You do not know why I am writing that to joomlafarsi. It was a reply to a mail from him containing a pack I tested and corrected which name contained the dash. It was in no way related to the way the download site format a pack to download at https://downloads.joomla.org/language-packs/translations-joomla4/downloads/

When one does not know, one does not comment.

**Comment by conconnl** [comment]
Then don’t use public issues for private discussions. 
I will close the issue, as this is a unnecessary of topic discussion as you clearly state it’s private and that other should shut up.
