### ISSUE TITLE
Arabic translation XML file

### ISSUE THREAD

**Issue by ChristineWk** [joomla/core-translations#831]
The following was reported in the Joomla forum de:  the version information is missing in the XML file in the Arabic language package. That's why it keeps asking for an update even though the current version has already been installed.

I sent this page to the user : https://volunteers.joomla.org/teams
https://volunteers.joomla.org/joomlers/564-private-profile-375901e3
regards
Christine

**Comment by tecpromotion** [comment]
Thanks. 

This must be fixed in crowdin and then in the self-created zip package.

**Comment by ChristineWk** [comment]
Is there anything else we have to do? I didn't know where to write above Issue. Was searching for :-)
Thank you

**Comment by tecpromotion** [comment]
You can register in crowdin and make a suggestion there.
I will also be happy to point it out to the proofreader.

**Comment by ChristineWk** [comment]
Aha Stefan. With new account or with my Github account?

**Comment by wojsmol** [comment]
@ChristineWk Crowdin offers login with github account - Joomla crowdin is here https://joomla.crowdin.com/

**Comment by ChristineWk** [comment]
Thank you! It wasn't possible at first. I had to log in to Github first, then I could go to Crowding.
