### ISSUE TITLE
Sinhala Language Pack

### ISSUE THREAD

**Issue by keminda** [joomla/core-translations#836]
Please add Sinhala Language pack to Joomla 4 and 5

**Comment by tecpromotion** [comment]
Hi @keminda 
The verified translation for sinhala is currently at 4%.
https://joomla.crowdin.com/u/projects/18/l/si

As soon as we are close to a finalised translation, we will be happy to integrate it. It's not really good as it is.

Unfortunately, the last time the responsible proofreader was logged into crowdin was 2 years ago.
If you are interested in the job, it would be a pleasure to deposit your crowdin user.
