### ISSUE TITLE
Danish sample data with not unique tag values

### ISSUE THREAD

**Issue by tkuschel** [joomla/core-translations#854]
According to https://issues.joomla.org/tracker/joomla-cms/42342
the Danish (da-DK) language the file
administrator/language/da-DK/plg_sampledata_blog.ini  is corrupt, b/c the lines with
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_0_TITLE  aso. have to be **unique** for the sample blog data installation!
Suggestion (but I'm not a native speaker):
```
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_0_TITLE="Millioner"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_1_TITLE="I hele verden"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_2_TITLE="Kærlighed"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_3_TITLE="Joomla 5"
```

I do not know if there is also another language file with equal tags in the repository?
Perhaps there an automated test to prevent this?
BTW the sample data are not translated from English to German (de-DE).

**Comment by tkuschel** [comment]
please follow upstream https://github.com/joomla/core-translations/issues/854

**Comment by tecpromotion** [comment]
Many thanks @tkuschel for pointing this out.
However, this must be adjusted in Crowdin at https://joomla.crowdin.com/u/projects/18/l/da.
This repo only syncs the status with Crowdin and is used to create PRs for the installation in the languages for the joomla-cms repo.

@rbuelund can you please have a look at this and if necessary make a fix in crowdin and then in the corresponding language pack. Thank you.
