### ISSUE TITLE
Dutch sample data with not unique tag values

### ISSUE THREAD

**Issue by fgsw** [joomla/core-translations#857]
#### Installation of Blog Sample Data using Dutch language fails at step 1:
![bsd-Dutch](https://github.com/joomla/core-translations/assets/147295380/5dd48df9-0ddc-40f4-988a-c7ce10bcf048)
#### Reason is using tag "Houden van" 2 times:
```
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_0_TITLE="Miljoenen"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_1_TITLE="Houden van"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_2_TITLE="Houden van"
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_TAG_3_TITLE="Joomla 5"
```

**Comment by tkuschel** [comment]
I changed the text of English Worldwide to Wereldwijd - hope this is okay!
The translation is done with https://joomla.crowdin.com/cms/nl 
Please check this translation, I'm a German native speaker.
@fgsw If there are more translation fixes needed, please edit in Crowdin yourself, thank you.
