### ISSUE TITLE
[5] Kazakh language installation fails

### ISSUE THREAD

**Issue by fgsw** [joomla/core-translations#858]
#### Installation Kazakh language fails 
```
JInstaller: :Install: Can't find Joomla XML setup file.
Unable to detect manifest file.
```
![Kazakh](https://github.com/joomla/core-translations/assets/147295380/1278bb49-214e-4e82-ac0d-32e06beee99f)

**Comment by tecpromotion** [comment]
@fgsw I can write to the proofreader responsible. But again, it won't be solved here.

**Comment by fgsw** [comment]
Issue solved, thanks all.

**Comment by tecpromotion** [comment]
> Issue solved, thanks all.

Thank you very much for your commitment.
