### ISSUE TITLE
[5] Hungarian, Thai: Blog sample data fails at step 2

### ISSUE THREAD

**Issue by fgsw** [joomla/core-translations#860]
#### Installation Blog sample data fails (Hungarian, Thai)
```
Data too long for column 'menutype' at row 1
```
Source string: ```PLG_SAMPLEDATA_BLOG_SAMPLEDATA_MENUS_ITEM_3_TITLE```

![-bsd-Hungarian-2](https://github.com/joomla/core-translations/assets/147295380/a7e6e156-c19e-495f-8a6c-e0eed724d05a)

![bsd-Thai-2](https://github.com/joomla/core-translations/assets/147295380/f1a01f7b-bffa-4f83-bc50-686f40a03ab7)

**Comment by tecpromotion** [comment]
The proofreaders have been informed. Thank you @fgsw 
You can also do this directly in crowdin. Thank you.
