### ISSUE TITLE
[5] Yellow Language Version in Latvian, Slovak

### ISSUE THREAD

**Issue by fgsw** [joomla/core-translations#863]
Latvian, Slovak language packs show a yellow language version:

![yellow-lang](https://github.com/joomla/core-translations/assets/147295380/bdd89ec7-2bd9-4378-990d-8e0047258923)

Like other language packs it should be ``` 5.0.0.x```, not ``` 5.0.1.x``` to match the Joomla version.

**Comment by tecpromotion** [comment]
The proofreaders have been informed. Thank you @fgsw 
You can also do this directly in crowdin. Thank you.

**Comment by fgsw** [comment]
> You can also do this directly in crowdin.

This?

![c](https://github.com/joomla/core-translations/assets/147295380/d2cb5799-3fe7-4a56-b995-e76ba44854b3)

**Comment by tecpromotion** [comment]
No, go to the corresponding language repo and to the relevant string. You can comment there.
Alternatively via the Volunteers Portal.

If in doubt, you can also do this here if you can't find a contact person. As Team Lead, I will of course also take care of it.
